#!/bin/sh

# BACKEND CHECKS
###########################

npm run precommit --prefix ./server
PRECOMMIT_EXIT="$?"

npm run auditCI --prefix ./server
AUDIT_EXIT="$?"

if [[ "${PRECOMMIT_EXIT}" == 0 && "${AUDIT_EXIT}" == 0  ]]; then
  echo ""
else
  printf "\nCOMMIT FAILED: Fix BACKEND errors and try again\n"
  exit 1
fi

# FRONTEND CHECKS
###########################

npm run precommit --prefix ./client
PRECOMMIT_EXIT="$?"

npm run auditCI --prefix ./client
AUDIT_EXIT="$?"

if [[ "${PRECOMMIT_EXIT}" == 0 && "${AUDIT_EXIT}" == 0 ]]; then
  echo ""
else
  printf "\nCOMMIT FAILED: Fix FRONTEND errors and try again\n"
  exit 1
fi

exit $?