#!/bin/sh

# BACKEND CHECKS
###########################

npm run precommit --prefix ./server
BACKEND_EXIT="$?"

if [[ "${BACKEND_EXIT}" == 0 ]]; then
  printf "\nSUCCESS: BACKEND\n"
else
  printf "\nCOMMIT FAILED: Fix BACKEND errors and try again\n"
  exit 1
fi

# FRONTEND CHECKS
###########################

npm run precommit --prefix ./client
FRONTEND_EXIT="$?"

if [[ "${FRONTEND_EXIT}" == 0 ]]; then
  printf "\nSUCCESS: FRONTEND\n"
else
  printf "\nCOMMIT FAILED: Fix FRONTEND errors and try again\n"
  exit 1
fi

exit $?