stages:
  - build
  - test
  - deploy
  - performance

testing:
  only:
    - master
  stage: test
  image: node:14.15.0
  before_script:
    - cd server
    - npm ci
    - cd ../client
    - npm ci
    - cd ..
  script:
    - cd server
    - npm run auditCI
    - npm run prettierCI
    - npm run lintCI
    - npm run lintTypescriptCI
    - npm run testCI
    - cd ../client
    - npm run auditCI
    - npm run prettierCI
    - npm run lintCI
    - npm run lintTypescriptCI
    - npm run testCI
