version: 2.1

jobs:
  backend:
    working_directory: ~/project/server
    docker:
      - image: cimg/node:14.15.0
    steps:
      - checkout:
          path: ~/project

      - restore_cache:
          name: Restore node modules cache
          key: backend-node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            if [ ! -d node_modules ]; then
              npm ci --ignore-scripts
            fi
      - save_cache:
          name: Save node modules cache
          key: backend-node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          command: npm run auditCI
      - run:
          command: npm run prettierCI
      - run:
          command: npm run lintCI
      - run:
          command: npm run lintTypescriptCI
      - run:
          command: npm run testCI
  frontend:
    working_directory: ~/project/client
    docker:
      - image: cimg/node:14.15.0
    steps:
      - checkout:
          path: ~/project

      - restore_cache:
          name: Restore node modules cache
          key: frontend-node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: |
            if [ ! -d node_modules ]; then
              npm ci --ignore-scripts
            fi
      - save_cache:
          name: Save node modules cache
          key: frontend-node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          command: npm run auditCI
      - run:
          command: npm run prettierCI
      - run:
          command: npm run lintCI
      - run:
          command: npm run lintTypescriptCI
      - run:
          command: npm run testCI
workflows:
  checks:
    jobs:
      - backend
      - frontend
